# Copyright (c) 2026. Tony Robalik.
# SPDX-License-Identifier: Apache-2.0
org.gradle.jvmargs=-Xmx1g -Dfile.encoding=UTF-8 -XX:+HeapDumpOnOutOfMemoryError -XX:MaxMetaspaceSize=1024m
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.kotlin.dsl.skipMetadataVersionCheck=false
org.gradle.parallel=true
org.gradle.isolated-projects=true

# The 'tapmocCheckKotlinMetadataVersions' task will fail unless this is set.
# https://github.com/gradle/gradle/issues/38790
org.gradle.unsafe.suppress-gradle-api=true

dependency.analysis.print.build.health=true
